### ISSUE TITLE
Peer Review - Ambiguous and Unmeasurable Requirement

### ISSUE THREAD

**Issue by edwarddgao** [ssm-lab/capstone--source-code-optimizer#154]
**Artifact Under Review**
FR-7

**Team Number for Team Doing the Review**
Team 3

**Description of Issue**
FR 2 states the system should detect "at least 80% of the following code smells" but doesn't specify how this will be measured or validated.

**Comment by Ayushi1972** [comment]
Metrics are defined in the document already. For this we have already defined that it will be detected using PySmells.
