### ISSUE TITLE
Peer Review - Relationships between classes in Business Data Model

### ISSUE THREAD

**Issue by richardl2003** [ssm-lab/capstone--source-code-optimizer#156]
**Artifact Under Review**
- 7.1 Business Data Model

**Team Number for Team Doing the Review**
- Team 3

**Description of Issue**
For the Business Data Model, it would be useful to indicate the types of relationships between the classes/entities
<img width="604" alt="image" src="https://github.com/user-attachments/assets/9e5127c6-bc58-4e29-be48-5b846b8225a2">
- E.g. this example showcases how some classes have a many-many, many-one relationship

**Comment by Sevhena** [comment]
An entity-relation type diagram is not appropriate in the context of our project. We chose a UML class diagram to show the hierarchy between classes and modules.

**Comment by richardl2003** [comment]
Yeah that makes sense, but even within UML class diagrams there can be multiplicities especially with abstract classes involved. Just a small nitpick tho, shouldn't really matter :)
